pipeline {
    agent { label 'pods' }

    environment {
        PROJECT_ZONE = "${JENK_INT_IT_ZONE}"
        PROJECT_ID = "${JENK_INT_IT_PROJECT_ID}"
        STAGING_CLUSTER = "${JENK_INT_IT_STAGING}"
        PROD_CLUSTER = "${JENK_INT_IT_PROD}"
        BUILD_CONTEXT_BUCKET = "${JENK_INT_IT_BUCKET}"
        BUILD_CONTEXT = "build-context-${BUILD_ID}.tar.gz"
        APP_NAME = "jenkins-integration-samples-gke"
        GCR_IMAGE = "gcr.io/${PROJECT_ID}/${APP_NAME}:${BUILD_ID}"
        APP_JAR = "${APP_NAME}.jar"
    }

    stages {
        stage("Build and test") {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    label 'maven-pod'
                    yamlFile 'gke/jenkins/maven-pod.yaml'
                }
            }
            steps {
                container('maven') {
                    dir("gke") {
                        sh "mvn clean package"
                        sh "mvn verify"
                        sh "cp target/${APP_NAME}-*.jar $APP_JAR"
                        sh "tar --exclude='./.git' -zcvf /tmp/$BUILD_CONTEXT ."
                        sh "mv /tmp/$BUILD_CONTEXT ."
                        step([
                            $class: 'ClassicUploadStep',
                            credentialsId: env.JENK_INT_IT_CRED_ID,
                            bucket: "gs://${BUILD_CONTEXT_BUCKET}",
                            pattern: env.BUILD_CONTEXT
                        ])
                    }
                }
            }
        }
    }
}
