pipeline {
    agent { label 'webs' }

    environment {
        PROJECT_ZONE = "${env.JENK_INT_IT_ZONE}"
        PROJECT_ID = "${env.JENK_INT_IT_PROJECT_ID}"
        STAGING_CLUSTER = "${env.JENK_INT_IT_STAGING}"
        PROD_CLUSTER = "${env.JENK_INT_IT_PROD}"
        BUILD_CONTEXT_BUCKET = "${env.JENK_INT_IT_BUCKET}"
        BUILD_CONTEXT = "build-context-${env.BUILD_ID}.tar.gz"
        APP_NAME = "jenkins-integration-samples-gke"
        GCR_IMAGE = "gcr.io/${env.PROJECT_ID}/${env.APP_NAME}:${env.BUILD_ID}"
        APP_JAR = "${env.APP_NAME}.jar"
    }

    tools {
        dockerTool 'docker1'
    }

    stages {
        stage("Build and test") {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    inheritFrom 'maven-pod'
                    yamlFile 'gke/jenkins/maven-pod.yaml'
                }
            }
            steps {
                container('maven') {
                    dir("gke") {
                        sh "mvn clean package"
                        sh "mvn verify"
                        sh "cp target/${env.APP_NAME}-*.jar ${env.APP_JAR}"
                        sh "tar --exclude='./.git' -zcvf /tmp/${env.BUILD_CONTEXT} ."
                        sh "mv /tmp/${env.BUILD_CONTEXT} ."
                        step([
                            $class: 'ClassicUploadStep',
                            credentialsId: env.JENK_INT_IT_CRED_ID,
                            bucket: "gs://${env.BUILD_CONTEXT_BUCKET}",
                            pattern: env.BUILD_CONTEXT
                        ])
                    }
                }
            }
        }

        stage("Publish Image") {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    label 'kaniko-pod'
                    yamlFile 'gke/jenkins/kaniko-pod.yaml'
                }
            }
            environment {
                PATH = "/busybox:/kaniko:$PATH"
            }
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    sh '''
                    #!/busybox/sh
                    /kaniko/executor -f `pwd`/gke/Dockerfile -c `pwd` \
                    --context="gs://${BUILD_CONTEXT_BUCKET}/${BUILD_CONTEXT}" \
                    --destination="${GCR_IMAGE}" --build-arg JAR_FILE="${APP_JAR}"
                    '''
                }
            }
        }

        stage("Deploy to staging") {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    label 'gke-deploy'
                    yamlFile 'gke/jenkins/gke-deploy-pod.yaml'
                }
            }
            steps {
                container('gke-deploy') {
                    sh "sed -i s#IMAGE#${env.GCR_IMAGE}#g gke/kubernetes/manifest.yaml"
                    step([
                        $class: 'KubernetesEngineBuilder',
                        projectId: env.PROJECT_ID,
                        clusterName: env.STAGING_CLUSTER,
                        location: env.PROJECT_ZONE,
                        manifestPattern: 'gke/kubernetes/manifest.yaml',
                        credentialsId: env.JENK_INT_IT_CRED_ID,
                        verifyDeployments: true
                    ])
                }
            }
        }

        /**
         * Uncomment the following stage if you want manual approval before deploying to production.
         *
        stage('Wait for SRE Approval') {
            steps {
                timeout(time: 12, unit: 'HOURS') {
                    input message: 'Approve deployment?'
                }
            }
        }
         **/

        stage("Deploy to prod") {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    label 'gke-deploy'
                    yamlFile 'gke/jenkins/gke-deploy-pod.yaml'
                }
            }
            steps {
                container('gke-deploy') {
                    sh "sed -i s#IMAGE#${env.GCR_IMAGE}#g gke/kubernetes/manifest.yaml"
                    step([
                        $class: 'KubernetesEngineBuilder',
                        projectId: env.PROJECT_ID,
                        clusterName: env.PROD_CLUSTER,
                        location: env.PROJECT_ZONE,
                        manifestPattern: 'gke/kubernetes/manifest.yaml',
                        credentialsId: env.JENK_INT_IT_CRED_ID,
                        verifyDeployments: true
                    ])
                }
            }
        }
    } // <-- Closing 'stages' block was missing
} // <-- Closing 'pipeline' block was missing
